### ISSUE TITLE
Medium Important - Logging Incidence by Age

### ISSUE THREAD

**Issue by maciekboni** [bonilab/Temple-Malaria-Simulation#6]
In the SQLiteDistrictReporter, a table is made called "monthlysitedata", and in this table there is a column called

   clinicalepisodes

that records all the symptomatic cases of malaria that occurred that month.  Can we break up this column by age, so that the clinical episodes output looks like:

   clinicalepisodes_0_1
   clinicalepisodes_1_2
   clinicalepisodes_2_5
   clinicalepisodes_5_10
   clinicalepisodes_10_15
   clinicalepisodes_15_20
   clinicalepisodes_20_99

and "5 to 10" means that the age is between 5.0 and 9.9999

and 20 to 99 obviously just has all individuals over 20.

Maybe this can be called SQLiteDistrictReporterByAge

**Comment by merlinvn** [comment]
This functionality was introduced in commit 40bdf36b4e117897cc31d780eed3b18b8e0c5590.

Age bands are determined by the values specified in the input files, leading to the automatic creation of corresponding columns in the table.

**Note:** If you modify the age bands in the input file, ensure to adjust related values (such as mortality by age class) to align with the updated age bands.

**Comment by maciekboni** [comment]
Excellent, thanks.  And is this in SQLiteDistrictReporter ?  Or, or in SQLiteDistrictReporterByAge ?

**Comment by merlinvn** [comment]
Just simply reuse the SQLiteDistrictReporter or SQLitePixelReporter. No new reporter has created.
